apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: nginx
    labels:
      app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: kuvshinov1616/nginx:1.0.1
        ports:
          - name: http
            containerPort: 8080
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.0.0
        env:
          - name: SCRAPE_URI
            value: "http://localhost:8080/basic_status"
        ports:
          - name: metrics
            containerPort: 9113