controller:
  replicaCount: 3

  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - ingress-nginx
          topologyKey: kubernetes.io/hostname

  nodeSelector: 
    yandex.cloud/node-group-id: cats4lt87lhq5lqp1gop
    
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"remote_addr":$remote_addr, "remote_user":"$remote_user", "time_local":"$time_local", "request":"$request", "status":"$status", "body_bytes_sent":"$body_bytes_sent", "http_referer":"$http_referer", "http_user_agent":"$http_user_agent", "request_length":"$request_length", "request_time":"$request_time", "proxy_upstream_name":"$proxy_upstream_name", "proxy_alternative_upstream_name":"$proxy_alternative_upstream_name", "upstream_addr":"$upstream_addr", "upstream_response_length":"$upstream_response_length", "upstream_response_time":"$upstream_response_time", "upstream_status":"$upstream_status", "req_id":"$req_id"}'